version: "3.8"

services:
  pg:
    container_name: pg
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: playercontrol
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.10-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

networks:
  default:
      name: service_player_control