version: "3.8"

services:
  pg:
    container_name: pg
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: playercontrol
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - .docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.10-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    hostname: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=pg
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=root
      - KEYCLOAK_DATABASE_PASSWORD=root
      - KEYCLOAK_DATABASE_SCHEMA=public
    volumes:
      - .docker/keycloak:/opt/keycloak/data/import
    restart: unless-stopped
    command:
      - start-dev --import-realm
    depends_on:
      - pg

networks:
  default:
      name: service_player_control