version: "3.8"

services:
  pg:
    container_name: pg
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: playercontrol
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
      name: service_player_control